# Generated by Django 4.1.4 on 2022-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="lat",
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="lng",
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
    ]
