# Generated by Django 4.1.4 on 2022-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_alter_restaurant_lat_alter_restaurant_lng"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("salads", "Salads"),
                            ("sandwiches", "Sandwiches"),
                            ("snacks", "Snacks"),
                            ("soups", "Soups"),
                            ("wraps", "Wraps"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["type", "name"],
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="food_items",
            field=models.ManyToManyField(to="places.fooditem"),
        ),
    ]
