# Generated by Django 4.1.4 on 2022-12-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_fooditem_menu_food_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="menus", to="places.restaurant"
            ),
        ),
    ]
