# Generated by Django 4.1.4 on 2022-12-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_menu_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="food_items",
            field=models.ManyToManyField(related_name="food_items", to="places.fooditem"),
        ),
    ]
