# Generated by Django 4.1.4 on 2022-12-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_menu_food_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="body",
        ),
    ]
