# Generated by Django 4.1.4 on 2022-12-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Votes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("votes_date", models.DateField(auto_now_add=True)),
                (
                    "employee",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="employees.employee"),
                ),
            ],
        ),
    ]
